name 'auacminstall'
maintainer 'John Harrison'
maintainer_email 'jwharrison007@gmail.com'
license 'all_rights'
description 'Installs and configures auacminstall'
long_description 'Installs and configures auacminstall'
version '0.1.0'
