name 'auacminstall'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures auacminstall'
long_description 'Installs/Configures auacminstall'
version '0.1.0'
